# Generated by Django 5.1.1 on 2024-12-06 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("image", models.CharField(db_column="Image", max_length=255)),
                ("name", models.CharField(db_column="Name", max_length=255)),
                ("price", models.IntegerField(db_column="Price")),
                (
                    "m_date",
                    models.DateField(
                        db_column="M_Date", verbose_name="Manufacture Date"
                    ),
                ),
                (
                    "e_date",
                    models.DateField(db_column="E_Date", verbose_name="Expiry Date"),
                ),
                ("status", models.CharField(db_column="Status", max_length=255)),
            ],
            options={
                "db_table": "product",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="Name",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "brand",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("ssn", models.CharField(db_column="SSN", max_length=255, unique=True)),
                ("name", models.CharField(db_column="Name", max_length=255)),
                ("address", models.CharField(db_column="Address", max_length=255)),
                ("phone", models.CharField(db_column="Phone", max_length=255)),
            ],
            options={
                "db_table": "customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DiscountProgram",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=255)),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=255, null=True
                    ),
                ),
                ("fromdate", models.DateField(db_column="FromDate")),
                ("todate", models.DateField(db_column="ToDate")),
                (
                    "percent",
                    models.DecimalField(
                        db_column="Percent", decimal_places=2, max_digits=10
                    ),
                ),
            ],
            options={
                "db_table": "discount_program",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ElectronicAccessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection",
                    models.CharField(db_column="Connection", max_length=255),
                ),
            ],
            options={
                "db_table": "electronic_accessories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("ssn", models.CharField(db_column="SSN", max_length=255, unique=True)),
                ("name", models.CharField(db_column="Name", max_length=255)),
            ],
            options={
                "db_table": "employee",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "type",
                    models.CharField(
                        db_column="Type",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "payment_method",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "no",
                    models.IntegerField(
                        db_column="No", primary_key=True, serialize=False
                    ),
                ),
                (
                    "requirement",
                    models.CharField(
                        blank=True, db_column="Requirement", max_length=255, null=True
                    ),
                ),
                (
                    "feedback",
                    models.CharField(
                        blank=True, db_column="Feedback", max_length=255, null=True
                    ),
                ),
                ("date", models.DateField(db_column="Date")),
            ],
            options={
                "db_table": "request",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, db_column="Date")),
                ("time", models.TimeField(auto_now_add=True, db_column="Time")),
                ("status", models.CharField(db_column="Status", max_length=255)),
                ("total", models.IntegerField(db_column="Total")),
            ],
            options={
                "db_table": "transaction",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "address",
                    models.CharField(
                        db_column="Address",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=255, null=True
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        db_column="Area",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "warehouse",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Applies",
            fields=[
                (
                    "p",
                    models.OneToOneField(
                        db_column="P_ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="store.product",
                    ),
                ),
                ("saving", models.IntegerField(db_column="Saving")),
            ],
            options={
                "db_table": "applies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Headphone",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="headphone",
                        serialize=False,
                        to="store.product",
                    ),
                ),
                ("type", models.CharField(db_column="Type", max_length=255)),
            ],
            options={
                "db_table": "headphone",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Keyboard",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="keyboard",
                        serialize=False,
                        to="store.product",
                    ),
                ),
                (
                    "switch_type",
                    models.CharField(db_column="Switch_Type", max_length=255),
                ),
                ("layout", models.CharField(db_column="Layout", max_length=255)),
            ],
            options={
                "db_table": "keyboard",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="laptop",
                        serialize=False,
                        to="store.product",
                    ),
                ),
                ("ram", models.CharField(db_column="RAM", max_length=255)),
                ("cpu", models.CharField(db_column="CPU", max_length=255)),
                (
                    "graphic_card",
                    models.CharField(db_column="Graphic_Card", max_length=255),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True, db_column="Purpose", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "laptop",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mouse",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mouse",
                        serialize=False,
                        to="store.product",
                    ),
                ),
                ("led_color", models.CharField(db_column="LED_Color", max_length=255)),
                ("dpi", models.IntegerField(db_column="DPI")),
            ],
            options={
                "db_table": "mouse",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Has",
            fields=[
                (
                    "b_name",
                    models.OneToOneField(
                        db_column="B_Name",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="store.brand",
                    ),
                ),
            ],
            options={
                "db_table": "has",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StoreManager",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="store.employee",
                    ),
                ),
            ],
            options={
                "db_table": "store_manager",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WarehouseManager",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="store.employee",
                    ),
                ),
            ],
            options={
                "db_table": "warehouse_manager",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ordered", models.DateTimeField(auto_now_add=True)),
                ("complete", models.BooleanField(default=False, null=True)),
                ("transaction_id", models.CharField(max_length=100, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.transaction",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.product",
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100, null=True)),
                ("street", models.CharField(max_length=100, null=True)),
                ("district", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.order",
                    ),
                ),
            ],
        ),
    ]
